### ISSUE TITLE
No CSV file generated 

### ISSUE THREAD

**Issue by spuder** [halloffame/ynab-csv#10]
When I upload a CSV file generated from Simple.com, nothing happens when I click "save YNAB Data"

I"ve tried on both Safari and Chrome multiple times. 

I can send in the CSV if it will help.

**Comment by wmeyers** [comment]
I have the same issue with Chrome and Safari!

Funnily, Firefox saves the file without a problem, and doesn't even save it as `.part` file.

**Comment by spuder** [comment]
I noticed some Chinese characters in my CSV, when I deleted those rows, it now works properly on Chrome. 

I've attached a sanitized CSV that shows the offending rows. 

https://dl.dropboxusercontent.com/u/460997/ynab-csv/2014-11-04-exported_transactions.csv

**Comment by halloffame** [comment]
There was a bug when the CSV file included non-latin characters. It should be fixed now https://github.com/halloffame/ynab-csv/issues/5
