### ISSUE TITLE
Inflow/Outflow in same column

### ISSUE THREAD

**Issue by itjustwerks** [halloffame/ynab-csv#11]
The CSV export I get from my bank has one column for the "amount", which is positive for Inflows, and negative for Outflows. It would be nice to have an option to handle this automatically.

**Comment by salvo2002** [comment]
+1

**Comment by noppermann** [comment]
+1

**Comment by halloffame** [comment]
This should already be happening, that is how the sample CSV file I have in this project is formatted https://github.com/halloffame/ynab-csv/blob/gh-pages/sample_data.csv. Can you please share the CSV file you are using in a public gist https://gist.github.com/ and reply to this thread with the public url.

**Comment by salvo2002** [comment]
just tried with my csv file from USAA bank where the inflows and outflows are in the same column and confirmed that it works.

![proof](https://cloud.githubusercontent.com/assets/10107638/6197397/0f86d4e2-b3aa-11e4-9557-b1bea7ca1ff5.png)

Sweet!

**Comment by halloffame** [comment]
@salvo2002 Cool! btw, it looks like your csv might not have a header row. So if it is dropping the first row that is why. If it doesn't work already, I want to add support for files without header rows at some time in the future.

**Comment by salvo2002** [comment]
Yes, I usually manually edit the csv and add a header row so it doesn't drop the first transaction. Support for that would be great but it's ok for now.
