### ISSUE TITLE
Missing Server.JS

### ISSUE THREAD

**Issue by bartn** [halloffame/ynab-csv#12]
I tried to run the source on my local machine using Node.JS as explained in the readme. However the repo doesn't include a server.js file.

**Comment by roanosullivan** [comment]
+1. I ended up forking the project in order to add a server.js and other scripts to make it easier to simply "clone and run" the project:

https://github.com/roanosullivan/ynab-csv/commit/00132ec719b3738b90f1d881739ffdf352f57359

**Comment by bartn** [comment]
Thanks Roano

**Comment by halloffame** [comment]
Thanks, not sure why that was in .gitignore.

**Comment by halloffame** [comment]
Just for the record, node isn't doing anything but acting as a dumb webserver in this project. So any webserver would do potentially. It just needs to serve up the static files.
