### ISSUE TITLE
Cannot save the new file

### ISSUE THREAD

**Issue by Galdifey** [halloffame/ynab-csv#2]
I tried Chrome and IE, but neither browser was able to save the file. Any thoughts?

**Comment by halloffame** [comment]
Chrome at the very least should work... try it with the sample csv file and let me know what you find. https://github.com/halloffame/ynab-csv/blob/gh-pages/sample_data.csv

**Comment by halloffame** [comment]
If I were to guess, it may have something to do with the format of your csv file. Could you post the file on https://gist.github.com/ and share the link? Make sure to remove/replace any data that is sensitive.

**Comment by Galdifey** [comment]
It took me a moment to get to the sample file. Don't ask ;)
Turns out my file only created the source data part, not the complete YNAB part. For the YNAB part I only see the drop down menus but not the actual data. So you are probably right that my file is somehow not working.

I copied the content of my file to github, but I'm new here, so I'm not sure if what I did was correct.
Here is the link:
https://gist.github.com/Galdifey/b36bd6d07d2f91eb6264

**Comment by Galdifey** [comment]
Here is a new try for the upload. Hopefully this time it is how it is supposed to be.

https://github.com/Galdifey/Galdifey/blob/master/banking.csv

**Comment by halloffame** [comment]
Sorry, I should have posted a link to the raw file :) https://raw.githubusercontent.com/halloffame/ynab-csv/gh-pages/sample_data.csv

Ok, thanks, yeah that's correct. I'll try to figure out what is causing that problem this weekend.

**Comment by Galdifey** [comment]
Thanks for your help.

**Comment by halloffame** [comment]
No problem :)

**Comment by halloffame** [comment]
This should be fixed now. One thing to note is that the site doesn't support files without a header row, so you will need to add a header row until I get that fixed. I've added an issue for that: https://github.com/halloffame/ynab-csv/issues/3

Thanks for letting me know about this!
