### ISSUE TITLE
Chrome download has no extension

### ISSUE THREAD

**Issue by talllguy** [halloffame/ynab-csv#4]
I processed some data with this tool (which is great. Good work! :clap: ), but the resulting download on my Mac via Chrome was called "download" with no extension.

**Comment by halloffame** [comment]
Yeah, I noticed that the other day too. I'll look into it when I get a chance, but for now you just have to rename it to `whatever_name_you_want.csv` before importing it into YNAB (though you may be able to import it without renaming it, I'm not sure). Thanks for creating this issue!

**Comment by halloffame** [comment]
@talllguy Sorry it has taken me so long to get to this. I just tried it out on the latest version of Chrome for mac and it downloaded as `ynab_data.csv`.

Are you still having this issue? Or did it fix itself? Let me know what version of chrome you are running if you are still having problems. Thanks!

**Comment by talllguy** [comment]
![2014-10-31 09_36_44-](https://cloud.githubusercontent.com/assets/1827881/4861432/09295fec-6103-11e4-89c5-0a3fdbd28392.png)

Sorry for the delay! Fixed.
