### ISSUE TITLE
Bug with cammas in amount totals

### ISSUE THREAD

**Issue by aquilentdev** [halloffame/ynab-csv#6]
Lines with commas in the amount total are dropped from the export.
Noticed this when converting a Paypal export with transactions or transfers of amounts of $1,000 or more.

**Comment by halloffame** [comment]
@aquilentdev Yep, you are right. Thanks for reporting that, I'll try to get that fixed.

Just so you know, you can export Quicken `(.qif)` files from Paypal which can be imported into ynab no problem.

**Comment by halloffame** [comment]
This issue should be fixed now. Thanks!
