### ISSUE TITLE
There is a report that this is not working on the latest version of chrome.

### ISSUE THREAD

**Issue by halloffame** [halloffame/ynab-csv#7]
Refer to the comment on https://github.com/halloffame/ynab-csv/issues/5 by @liab.

> I am not able to generate the YNAB csv from Chrome. It worked till 2 days ago, but now is not working anymore. I've tried in another computer, but no luck. What should I do?

**Comment by halloffame** [comment]
@liab, sorry it has taken me so long to look at this. I just tried it out with the `sample.csv` file and it worked fine. I used Chrome for mac. 

If you can, create a gist (https://gist.github.com/) with the file that is giving you trouble and put the link here and I'll take a look at it.

**Comment by hamkicker** [comment]
I have the same problem too.  My CSV has Japanese characters in it, and the "Save YNAB Data" button doesn't do anything.

**Comment by halloffame** [comment]
Hm, maybe this _is_ the same issue as #5 . I'm going to close this issue for now and focus on that one. @hamkicker If you can send me a sample CSV file with the special characters in it that would be great. Please link to it in the discussion for issue #5. Thanks!

**Comment by halloffame** [comment]
@liab, if you are still having problems that are unrelated to having special characters in your CSV file, let me know the details and I will reopen this issue. And please include the problem CSV file.

**Comment by liab** [comment]
@halloffame Sorry, I had no time to check on this till now. I am still having issue, there is no special characters in my file. I use Windows, I can load the data and select the columns. Chrome shows the data, but the "save to YNAB" does not work. Here the sample https://gist.github.com/d038aad8e21fc3d8833a.git
