### ISSUE TITLE
It doesn't recognize the non-US date format

### ISSUE THREAD

**Issue by ghost** [halloffame/ynab-csv#9]
Hello!
Great tool! Thanks.

Recently Inoticed that it doesn't recognise a date any longer?! Potentialy beasue the bank has changed the way they export CSV. My date format is DD/MM/YYYY - the program says that the date is invalid.
Can you make a date format selection on the screen as well?

Thank you in advance!

**Comment by bartn** [comment]
Exactly the same thing I ran into. Tried to fork the repo but there was no server.js that I could run with NodeJs.

**Comment by noppermann** [comment]
+1

**Comment by timwredwards** [comment]
+1

**Comment by Bastar** [comment]
+1

**Comment by jonnyparris** [comment]
+1

**Comment by kotoponus** [comment]
Ditto.  DD/MM/YYYY for my case!

**Comment by luzhanov** [comment]
Also it would be great to choose delimiter (`,` or `;`) - now I have a problem with importing because i have a commas in `Memo` field

**Comment by DonnchaC** [comment]
:+1:

**Comment by brendanmullan** [comment]
+1
